services:
  spaceship-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  db:
    image: buildo/h2database
    ports:
      - "9092:9092"
    environment:
      H2_OPTIONS: -tcpAllowOthers
